export const DIGITAL = {
  name: 'Цифровой иммунитет',
  subname: 'Учись, Играй, Будь в безопасности',
  photo: 'digital',
  date: '18 августа 2025 – 28 февраля 2026',
  description: [
    'Наша заявка стала победителем второго конкурса Фонда Президентских грантов 2025 и этот проект стал первой грантовой историей в нашей организации.',
    'Проект направлен на обучение детей из многодетных семей, обучающихся в 8-11 классах общеобразовательных школ города Горловки навыкам пользования офисных программ Microsoft Office (Word, Excel, PowerPoint), а также основам кибербезопасности и противостояния кибербуллингу, закладывание в подростков идей о морали в интернете, а также обучение азам гимнастики для поддержания физической формы и избежания болезней при длительной работе за компьютером.',
  ],
  team: [
    {
      id: 1,
      surname: 'Трухачев',
      name: 'Александр Сергеевич',
      photo: 'persona6',
      post: 'Учитель информатики',
      type: 'small',
      description:
        '35 уроков по обучению детей навыкам работы с офисными программами Microsoft Office (Word, Excel, PowerPoint)',
    },
    {
      id: 2,
      surname: 'Хорьяков',
      name: 'Станислав Владимирович',
      photo: 'persona4',
      post: 'Учитель физкультуры',
      type: 'small',
      description:
        'Проведение 6 физкульт занятий по 20 мин с целью обучить детей комплексу упражнений, необходимых для сохранения здоровья при длительной работе с компьютером.',
    },
    {
      id: 3,
      surname: 'Павлова',
      name: 'Вита Викторовна',
      photo: 'persona7',
      post: 'Педагог-психолог ЦППМСП г.о Горловка',
      type: 'small',
      description:
        'Проведение 7 встреч на тему кибербуллинга и противостоянию этому вредоносному явлению',
    },
    {
      id: 4,
      surname: 'Протоиерей',
      name: 'Михаил Фоменко',
      photo: 'persona8',
      post: 'Священник',
      type: 'small',
      description:
        'Проведение 5 встреч на тему нравственности и морали в интернете',
    },
    {
      id: 5,
      surname: 'Священник',
      name: 'Евгений Тимофеев',
      photo: 'persona9',
      post: 'Священник, аспирант СПбДА',
      type: 'small',
      description:
        'Проведение 2 встреч в формате видеоконференции на тему «совесть в режиме инкогнито»',
    },
  ],
  partners: {
    bfStrana: 'БФ "Страна для детей"',
    vesti: 'Вести Донецк',
    kochegarka: 'Газета "Кочегарка ДНР"',
    gorlovkaAdmin: 'Администрация г.о. Горловка',
    gorlovkaObr: 'Управление образования г.о. Горловка',
  },
  finance: {
    'Cредства предоставлены Фондом президентских грантов': 471891.3,
    'Софинансирование': 204090.0,
  },
  photos: {
    step5_1: [
      'digital/step5_1_01.webp',
      'digital/step5_1_02.webp',
      'digital/step5_1_03.webp',
      'digital/step5_1_04.webp',
      'digital/step5_2_01.webp',
      'digital/step5_2_02.webp',
      'digital/step5_2_03.webp',
      'digital/step5_2_04.webp',
    ],
    step5_3: ['digital/step5_3_01.webp'],
    step5_4: ['digital/step5_4_01.webp', 'digital/step5_4_02.webp'],
    step5_5: [
      'digital/step5_5_01.webp',
      'digital/step5_5_02.webp',
      'digital/step5_5_03.webp',
      'digital/step5_5_04.webp',
      'digital/step5_5_05.webp',
    ],
    step5_0: [
      'digital/step5_0_01.webp',
      'digital/step5_0_02.webp',
      'digital/step5_0_03.webp',
      'digital/step5_0_04.webp',
      'digital/step5_0_05.webp',
      'digital/step5_0_06.webp',
      'digital/step5_0_07.webp',
    ],
    step4_1: [
      {
        type: 'photo',
        photo: 'digital/step4_1_09_18_01.webp',
        date: '18/09/2025',
      },
      {
        type: 'photo',
        photo: 'digital/step4_1_09_18_02.webp',
        date: '18/09/2025',
      },
      {
        type: 'photo',
        photo: 'digital/step4_1_09_23_01.webp',
        date: '23/09/2025',
      },
      {
        type: 'video',
        photo: 'digital/v_02.webp',
        link: 'https://vk.com/video_ext.php?oid=-229630779&id=456239024&hd=1',
        date: '23/09/2025',
      },
      {
        type: 'photo',
        photo: 'digital/step4_1_09_30_01.webp',
        date: '30/09/2025',
      },
      'digital/step4_1_10_01.webp',
      'digital/step4_1_10_02.webp',
    ],
    step4_2: [
      {
        type: 'photo',
        photo: 'digital/step4_2_09_18_01.webp',
        date: '18/09/2025',
      },
      {
        type: 'video',
        photo: 'digital/v_01.webp',
        link: 'https://vk.com/video_ext.php?oid=-229630779&id=456239025&hd=3',
        date: '23/09/2025',
      },
      {
        type: 'photo',
        photo: 'digital/step4_2_10_02_01.webp',
        date: '02/10/2025',
      },
    ],
    step4_3: [
      'digital/step4_3_01.webp',
      'digital/step4_3_02.webp',
      'digital/step4_3_03.webp',
      'digital/step4_3_04.webp',
    ],
    step4_4: ['digital/step4_4_01.webp', 'digital/step4_4_02.webp'],
    step4_5: [
      'digital/step4_5_01.webp',
      'digital/step4_5_02.webp',
      'digital/step4_5_03.webp',
      'digital/step4_5_04.webp',
    ],
    step4_6: [
      'digital/step4_6_01.webp',
      'digital/step4_6_02.webp',
      'digital/step4_6_03.webp',
      {
        type: 'video',
        photo: 'digital/v_03.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239061&hash=bc4c247a0430edd4&hd=3',
        date: 'Тема 1',
      },
      {
        type: 'video',
        photo: 'digital/v_04.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239062&hash=d41cd3689a487616&hd=3',
        date: 'Тема 2',
      },
      {
        type: 'video',
        photo: 'digital/v_05.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239063&hash=901954a8d2cdff47&hd=3',
        date: 'Тема 3',
      },
      {
        type: 'video',
        photo: 'digital/v_06.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239064&hash=b41bd7ea80b71581&hd=3',
        date: 'Тема 4',
      },
      {
        type: 'video',
        photo: 'digital/v_07.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239068&hash=193e045d2a7ed303&hd=3',
        date: 'Тема 5',
      },
      {
        type: 'video',
        photo: 'digital/v_08.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239069&hash=8640ea8671a9e86a&hd=3',
        date: 'Тема 6',
      },
      {
        type: 'video',
        photo: 'digital/v_09.webp',
        link: 'https://vkvideo.ru/video_ext.php?oid=-229630779&id=456239074&hash=3e23635903256dbf&hd=3',
        date: 'Тема 7',
      },
    ],
    step3_1: [
      'digital/step3_1_01.webp',
      'digital/step3_1_02.webp',
      'digital/step3_1_03.webp',
      'digital/step3_1_04.webp',
    ],
    step3_2: [
      'digital/step3_2_01.webp',
      'digital/step3_2_02.webp',
      'digital/step3_2_03.webp',
    ],
    step3_3: ['digital/step3_3_01.webp', 'digital/step3_3_02.webp'],
    step3_4: [
      'digital/step3_4_01.webp',
      'digital/step3_4_02.webp',
      'digital/step3_4_03.webp',
      'digital/step3_4_04.webp',
    ],
    step3_5: ['digital/step3_5_01.webp', 'digital/step3_5_02.webp'],
    step2_1: [
      'digital/step2_1_01.webp',
      'digital/step2_1_02.webp',
      'digital/step2_1_03.webp',
      'digital/step2_1_04.webp',
    ],
    step2_2: [
      'digital/step2_2_01.webp',
      'digital/step2_2_02.webp',
      'digital/step2_2_03.webp',
      'digital/step2_2_04.webp',
    ],
    step1: [
      'digital/step1_01.webp',
      'digital/step1_02.webp',
      'digital/step1_03.webp',
    ],
  },
};
